name: CD

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build
        env:
          NODE_ENV: production

      - uses: actions/upload-artifact@v2.2.3
        with:
          name: dist
          path: dist

  netlify-deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v2.0.9
        with:
          name: dist
          path: dist

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      - name: Install netlify
        run: npm install -g netlify-cli

      - name: Deploy
        run: netlify deploy --prod -d dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEPLOY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
