name: CD

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build
        env:
          NODE_ENV: production

      - uses: actions/upload-artifact@v2.2.4
        with:
          name: public
          path: public

  netlify-deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v2.0.10
        with:
          name: public
          path: public

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 12.x

      - name: Install netlify
        run: npm install -g netlify-cli

      - name: Deploy
        run: netlify deploy --prod -d public
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_DEPLOY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
