name: CI

on:
  push:
    branches: [main, develop]
    paths-ignore: 
      - 'README.md'
      - 'LICENSE'
      - 'img/**'
      - '.github/workflows/codeql-analysis.yml'
      - '.github/workflows/CD.yml'
      
  pull_request:
    branches: [main, develop]
    paths-ignore: 
      - 'README.md'
      - 'LICENSE'
      - 'img/**'
      - '.github/workflows/codeql-analysis.yml'
      - '.github/workflows/CD.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12', '14', '16']

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Build App
        run: npm run build
        env:
          NODE_ENV: production
